url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Galen Guyer" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-tidy

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bake.sh
  - Dockerfile
  - Dockerfile.files
  - docker-bake.hcl
